export const RADIO_NAMES_LOAD_INIT = "RADIO_NAMES_LOAD_INIT";
export const RADIO_NAMES_LOAD_SUCCEED = "RADIO_NAMES_LOAD_SUCCEED";
export const RADIO_NAMES_LOAD_FAILED = "RADIO_NAMES_LOAD_FAILED";

export const RADIO_LOAD_INIT = "RADIO_LOAD_INIT";
export const RADIO_LOAD_SUCCEED = "RADIO_LOAD_SUCCEED";
export const RADIO_LOAD_FAILED = "RADIO_LOAD_FAILED";

export const ENTITY_LOAD_INIT = "ENTITY_LOAD_INIT";
export const ENTITY_LOAD_SUCCEED = "ENTITY_LOAD_SUCCEED";
export const ENTITY_LOAD_FAILED = "ENTITY_LOAD_FAILED";

export const ADD_BROADCAST_INIT = "ADD_BROADCAST_INIT";
export const ADD_BROADCAST_SUCCEED = "ADD_BROADCAST_SUCCEED";
export const ADD_BROADCAST_FAILED = "ADD_BROADCAST_FAILED";

export const ADD_RADIO_STATION_INIT = "ADD_RADIO_STATION_INIT";
export const ADD_RADIO_STATION_SUCCEED = "ADD_RADIO_STATION_SUCCEED";
export const ADD_RADIO_STATION_FAILED = "ADD_RADIO_STATION_FAILED";

export const SAVE_INIT = "SAVE_INIT";
export const SAVE_SUCCEED = "SAVE_SUCCEED";
export const SAVE_FAILED = "SAVE_FAILED";

export const DELETE_BROADCAST_INIT = "DELETE_BROADCAST_INIT";
export const DELETE_BROADCAST_SUCCEED = "DELETE_BROADCAST_SUCCEED";
export const DELETE_BROADCAST_FAILED = "DELETE_BROADCAST_FAILED";

export const DELETE_RADIO_STATION_INIT = "DELETE_RADIO_STATION_INIT";
export const DELETE_RADIO_STATION_SUCCEED = "DELETE_RADIO_STATION_SUCCEED";
export const DELETE_RADIO_STATION_FAILED = "DELETE_RADIO_STATION_FAILED";

export const SET_BROADCAST_DETAIL = "SET_BROADCAST_DETAIL";
