export const PROJECTS_LINKS_LOAD_INIT = "PROJECTS_LINKS_LOAD_INIT";
export const PROJECTS_LINKS_LOAD_SUCCEED = "PROJECTS_LINKS_LOAD_SUCCEED";
export const PROJECTS_LINKS_LOAD_FAILED = "PROJECTS_LINKS_LOAD_FAILED";

export const PROJECTS_LINK_SAVE_INIT = "PROJECTS_LINK_SAVE_INIT";
export const PROJECTS_LINK_SAVE_SUCCEED = "PROJECTS_LINK_SAVE_SUCCEED";
export const PROJECTS_LINK_SAVE_FAILED = "PROJECTS_LINK_SAVE_FAILED";

export const PROJECTS_LINK_DELETE_INIT = "PROJECTS_LINK_DELETE_INIT";
export const PROJECTS_LINK_DELETE_SUCCEED = "PROJECTS_LINK_DELETE_SUCCEED";
export const PROJECTS_LINK_DELETE_FAILED = "PROJECTS_LINK_DELETE_FAILED";
