export const CONTACTS_LINKS_LOAD_INIT = "CONTACTS_LINKS_LOAD_INIT";
export const CONTACTS_LINKS_LOAD_SUCCEED = "CONTACTS_LINKS_LOAD_SUCCEED";
export const CONTACTS_LINKS_LOAD_FAILED = "CONTACTS_LINKS_LOAD_FAILED";

export const CONTACTS_LINK_SAVE_INIT = "CONTACTS_LINK_SAVE_INIT";
export const CONTACTS_LINK_SAVE_SUCCEED = "CONTACTS_LINK_SAVE_SUCCEED";
export const CONTACTS_LINK_SAVE_FAILED = "CONTACTS_LINK_SAVE_FAILED";

export const CONTACTS_LINK_DELETE_INIT = "CONTACTS_LINK_DELETE_INIT";
export const CONTACTS_LINK_DELETE_SUCCEED = "CONTACTS_LINK_DELETE_SUCCEED";
export const CONTACTS_LINK_DELETE_FAILED = "CONTACTS_LINK_DELETE_FAILED";
