export const CONTACT_LINKS_LOAD_INIT = "CONTACT_LINKS_LOAD_INIT";
export const CONTACT_LINKS_LOAD_SUCCEED = "CONTACT_LINKS_LOAD_SUCCEED";
export const CONTACT_LINKS_LOAD_FAILED = "CONTACT_LINKS_LOAD_FAILED";

export const CONTACT_LINK_SAVE_INIT = "CONTACT_LINK_SAVE_INIT";
export const CONTACT_LINK_SAVE_SUCCEED = "CONTACT_LINK_SAVE_SUCCEED";
export const CONTACT_LINK_SAVE_FAILED = "CONTACT_LINK_SAVE_FAILED";

export const CONTACT_LINK_DELETE_INIT = "CONTACT_LINK_DELETE_INIT";
export const CONTACT_LINK_DELETE_SUCCEED = "CONTACT_LINK_DELETE_SUCCEED";
export const CONTACT_LINK_DELETE_FAILED = "CONTACT_LINK_DELETE_FAILED";
