export const DAC_LINKS_LOAD_INIT = "DAC_LINKS_LOAD_INIT";
export const DAC_LINKS_LOAD_SUCCEED = "DAC_LINKS_LOAD_SUCCEED";
export const DAC_LINKS_LOAD_FAILED = "DAC_LINKS_LOAD_FAILED";

export const DAC_LINK_SAVE_INIT = "DAC_LINK_SAVE_INIT";
export const DAC_LINK_SAVE_SUCCEED = "DAC_LINK_SAVE_SUCCEED";
export const DAC_LINK_SAVE_FAILED = "DAC_LINK_SAVE_FAILED";

export const DAC_LINK_DELETE_INIT = "DAC_LINK_DELETE_INIT";
export const DAC_LINK_DELETE_SUCCEED = "DAC_LINK_DELETE_SUCCEED";
export const DAC_LINK_DELETE_FAILED = "DAC_LINK_DELETE_FAILED";
