export const CD_LINKS_LOAD_INIT = "CD_LINKS_LOAD_INIT";
export const CD_LINKS_LOAD_SUCCEED = "CD_LINKS_LOAD_SUCCEED";
export const CD_LINKS_LOAD_FAILED = "CD_LINKS_LOAD_FAILED";

export const CD_LINK_SAVE_INIT = "CD_LINK_SAVE_INIT";
export const CD_LINK_SAVE_SUCCEED = "CD_LINK_SAVE_SUCCEED";
export const CD_LINK_SAVE_FAILED = "CD_LINK_SAVE_FAILED";

export const CD_LINK_DELETE_INIT = "CD_LINK_DELETE_INIT";
export const CD_LINK_DELETE_SUCCEED = "CD_LINK_DELETE_SUCCEED";
export const CD_LINK_DELETE_FAILED = "CD_LINK_DELETE_FAILED";
