export const INFOSERVICE_LINKS_LOAD_INIT = "INFOSERVICE_LINKS_LOAD_INIT";
export const INFOSERVICE_LINKS_LOAD_SUCCEED = "INFOSERVICE_LINKS_LOAD_SUCCEED";
export const INFOSERVICE_LINKS_LOAD_FAILED = "INFOSERVICE_LINKS_LOAD_FAILED";

export const INFOSERVICE_LINK_SAVE_INIT = "INFOSERVICE_LINK_SAVE_INIT";
export const INFOSERVICE_LINK_SAVE_SUCCEED = "INFOSERVICE_LINK_SAVE_SUCCEED";
export const INFOSERVICE_LINK_SAVE_FAILED = "INFOSERVICE_LINK_SAVE_FAILED";

export const INFOSERVICE_LINK_DELETE_INIT = "INFOSERVICE_LINK_DELETE_INIT";
export const INFOSERVICE_LINK_DELETE_SUCCEED =
    "INFOSERVICE_LINK_DELETE_SUCCEED";
export const INFOSERVICE_LINK_DELETE_FAILED = "INFOSERVICE_LINK_DELETE_FAILED";
