export const COOPERATIVES_LINKS_LOAD_INIT = "COOPERATIVES_LINKS_LOAD_INIT";
export const COOPERATIVES_LINKS_LOAD_SUCCEED =
    "COOPERATIVES_LINKS_LOAD_SUCCEED";
export const COOPERATIVES_LINKS_LOAD_FAILED = "COOPERATIVES_LINKS_LOAD_FAILED";

export const COOPERATIVES_LINK_SAVE_INIT = "COOPERATIVES_LINK_SAVE_INIT";
export const COOPERATIVES_LINK_SAVE_SUCCEED = "COOPERATIVES_LINK_SAVE_SUCCEED";
export const COOPERATIVES_LINK_SAVE_FAILED = "COOPERATIVES_LINK_SAVE_FAILED";

export const COOPERATIVES_LINK_DELETE_INIT = "COOPERATIVES_LINK_DELETE_INIT";
export const COOPERATIVES_LINK_DELETE_SUCCEED =
    "COOPERATIVES_LINK_DELETE_SUCCEED";
export const COOPERATIVES_LINK_DELETE_FAILED =
    "COOPERATIVES_LINK_DELETE_FAILED";
