export const CLASSROOM_NAMES_LOAD_INIT = "CLASSROOM_NAMES_LOAD_INIT";
export const CLASSROOM_NAMES_LOAD_SUCCEED = "CLASSROOM_NAMES_LOAD_SUCCEED";
export const CLASSROOM_NAMES_LOAD_FAILED = "CLASSROOM_NAMES_LOAD_FAILED";

export const CLASSROOM_LOAD_INIT = "CLASSROOM_LOAD_INIT";
export const CLASSROOM_LOAD_SUCCEED = "CLASSROOM_LOAD_SUCCEED";
export const CLASSROOM_LOAD_FAILED = "CLASSROOM_LOAD_FAILED";

export const CLASSROOM_ENTITY_LOAD_INIT = "CLASSROOM_ENTITY_LOAD_INIT";
export const CLASSROOM_ENTITY_LOAD_SUCCEED = "CLASSROOM_ENTITY_LOAD_SUCCEED";
export const CLASSROOM_ENTITY_LOAD_FAILED = "CLASSROOM_ENTITY_LOAD_FAILED";

export const ADD_CLASSROOM_INIT = "ADD_CLASSROOM_INIT";
export const ADD_CLASSROOM_SUCCEED = "ADD_CLASSROOM_SUCCEED";
export const ADD_CLASSROOM_FAILED = "ADD_CLASSROOM_FAILED";

export const SAVE_INIT = "SAVE_INIT";
export const SAVE_SUCCEED = "SAVE_SUCCEED";
export const SAVE_FAILED = "SAVE_FAILED";

export const DELETE_COURSE_INIT = "DELETE_COURSE_INIT";
export const DELETE_COURSE_SUCCEED = "DELETE_COURSE_SUCCEED";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";

export const DELETE_CLASSROOM_INIT = "DELETE_CLASSROOM_INIT";
export const DELETE_CLASSROOM_SUCCEED = "DELETE_CLASSROOM_SUCCEED";
export const DELETE_CLASSROOM_FAILED = "DELETE_CLASSROOM_FAILED";

export const SET_COURSE_DETAIL = "SET_COURSE_DETAIL";
