export const PLATFORMS_LINKS_LOAD_INIT = "PLATFORMS_LINKS_LOAD_INIT";
export const PLATFORMS_LINKS_LOAD_SUCCEED = "PLATFORMS_LINKS_LOAD_SUCCEED";
export const PLATFORMS_LINKS_LOAD_FAILED = "PLATFORMS_LINKS_LOAD_FAILED";

export const PLATFORMS_LINK_SAVE_INIT = "PLATFORMS_LINK_SAVE_INIT";
export const PLATFORMS_LINK_SAVE_SUCCEED = "PLATFORMS_LINK_SAVE_SUCCEED";
export const PLATFORMS_LINK_SAVE_FAILED = "PLATFORMS_LINK_SAVE_FAILED";

export const PLATFORMS_LINK_DELETE_INIT = "PLATFORMS_LINK_DELETE_INIT";
export const PLATFORMS_LINK_DELETE_SUCCEED = "PLATFORMS_LINK_DELETE_SUCCEED";
export const PLATFORMS_LINK_DELETE_FAILED = "PLATFORMS_LINK_DELETE_FAILED";
