export const AFFILIATIONS_LINKS_LOAD_INIT = "AFFILIATIONS_LINKS_LOAD_INIT";
export const AFFILIATIONS_LINKS_LOAD_SUCCEED =
    "AFFILIATIONS_LINKS_LOAD_SUCCEED";
export const AFFILIATIONS_LINKS_LOAD_FAILED = "AFFILIATIONS_LINKS_LOAD_FAILED";

export const AFFILIATIONS_LINK_SAVE_INIT = "AFFILIATIONS_LINK_SAVE_INIT";
export const AFFILIATIONS_LINK_SAVE_SUCCEED = "AFFILIATIONS_LINK_SAVE_SUCCEED";
export const AFFILIATIONS_LINK_SAVE_FAILED = "AFFILIATIONS_LINK_SAVE_FAILED";

export const AFFILIATIONS_LINK_DELETE_INIT = "AFFILIATIONS_LINK_DELETE_INIT";
export const AFFILIATIONS_LINK_DELETE_SUCCEED =
    "AFFILIATIONS_LINK_DELETE_SUCCEED";
export const AFFILIATIONS_LINK_DELETE_FAILED =
    "AFFILIATIONS_LINK_DELETE_FAILED";
