export const PE_LINKS_LOAD_INIT = "PE_LINKS_LOAD_INIT";
export const PE_LINKS_LOAD_SUCCEED = "PE_LINKS_LOAD_SUCCEED";
export const PE_LINKS_LOAD_FAILED = "PE_LINKS_LOAD_FAILED";

export const PE_LINK_SAVE_INIT = "PE_LINK_SAVE_INIT";
export const PE_LINK_SAVE_SUCCEED = "PE_LINK_SAVE_SUCCEED";
export const PE_LINK_SAVE_FAILED = "PE_LINK_SAVE_FAILED";

export const PE_LINK_DELETE_INIT = "PE_LINK_DELETE_INIT";
export const PE_LINK_DELETE_SUCCEED = "PE_LINK_DELETE_SUCCEED";
export const PE_LINK_DELETE_FAILED = "PE_LINK_DELETE_FAILED";
