export const JOBBANK_LINKS_LOAD_INIT = "JOBBANK_LINKS_LOAD_INIT";
export const JOBBANK_LINKS_LOAD_SUCCEED = "JOBBANK_LINKS_LOAD_SUCCEED";
export const JOBBANK_LINKS_LOAD_FAILED = "JOBBANK_LINKS_LOAD_FAILED";

export const JOBBANK_LINK_SAVE_INIT = "JOBBANK_LINK_SAVE_INIT";
export const JOBBANK_LINK_SAVE_SUCCEED = "JOBBANK_LINK_SAVE_SUCCEED";
export const JOBBANK_LINK_SAVE_FAILED = "JOBBANK_LINK_SAVE_FAILED";

export const JOBBANK_LINK_DELETE_INIT = "JOBBANK_LINK_DELETE_INIT";
export const JOBBANK_LINK_DELETE_SUCCEED = "JOBBANK_LINK_DELETE_SUCCEED";
export const JOBBANK_LINK_DELETE_FAILED = "JOBBANK_LINK_DELETE_FAILED";
