export const SCHEDULE_LINKS_LOAD_INIT = "SCHEDULE_LINKS_LOAD_INIT";
export const SCHEDULE_LINKS_LOAD_SUCCEED = "SCHEDULE_LINKS_LOAD_SUCCEED";
export const SCHEDULE_LINKS_LOAD_FAILED = "SCHEDULE_LINKS_LOAD_FAILED";

export const SCHEDULE_LINK_SAVE_INIT = "SCHEDULE_LINK_SAVE_INIT";
export const SCHEDULE_LINK_SAVE_SUCCEED = "SCHEDULE_LINK_SAVE_SUCCEED";
export const SCHEDULE_LINK_SAVE_FAILED = "SCHEDULE_LINK_SAVE_FAILED";

export const SCHEDULE_LINK_DELETE_INIT = "SCHEDULE_LINK_DELETE_INIT";
export const SCHEDULE_LINK_DELETE_SUCCEED = "SCHEDULE_LINK_DELETE_SUCCEED";
export const SCHEDULE_LINK_DELETE_FAILED = "SCHEDULE_LINK_DELETE_FAILED";
