export const ACCESSIONS_LINKS_LOAD_INIT = "ACCESSIONS_LINKS_LOAD_INIT";
export const ACCESSIONS_LINKS_LOAD_SUCCEED = "ACCESSIONS_LINKS_LOAD_SUCCEED";
export const ACCESSIONS_LINKS_LOAD_FAILED = "ACCESSIONS_LINKS_LOAD_FAILED";

export const ACCESSIONS_LINK_SAVE_INIT = "ACCESSIONS_LINK_SAVE_INIT";
export const ACCESSIONS_LINK_SAVE_SUCCEED = "ACCESSIONS_LINK_SAVE_SUCCEED";
export const ACCESSIONS_LINK_SAVE_FAILED = "ACCESSIONS_LINK_SAVE_FAILED";

export const ACCESSIONS_LINK_DELETE_INIT = "ACCESSIONS_LINK_DELETE_INIT";
export const ACCESSIONS_LINK_DELETE_SUCCEED = "ACCESSIONS_LINK_DELETE_SUCCEED";
export const ACCESSIONS_LINK_DELETE_FAILED = "ACCESSIONS_LINK_DELETE_FAILED";
