export const CONSOLE_LINKS_LOAD_INIT = "CONSOLE_LINKS_LOAD_INIT";
export const CONSOLE_LINKS_LOAD_SUCCEED = "CONSOLE_LINKS_LOAD_SUCCEED";
export const CONSOLE_LINKS_LOAD_FAILED = "CONSOLE_LINKS_LOAD_FAILED";

export const CONSOLE_LINK_SAVE_INIT = "CONSOLE_LINK_SAVE_INIT";
export const CONSOLE_LINK_SAVE_SUCCEED = "CONSOLE_LINK_SAVE_SUCCEED";
export const CONSOLE_LINK_SAVE_FAILED = "CONSOLE_LINK_SAVE_FAILED";

export const CONSOLE_LINK_DELETE_INIT = "CONSOLE_LINK_DELETE_INIT";
export const CONSOLE_LINK_DELETE_SUCCEED = "CONSOLE_LINK_DELETE_SUCCEED";
export const CONSOLE_LINK_DELETE_FAILED = "CONSOLE_LINK_DELETE_FAILED";

export const CONSOLE_SET_ENTITY = "CONSOLE_SET_ENTITY";
