export const PROCEDURES_LINKS_LOAD_INIT = "PROCEDURES_LINKS_LOAD_INIT";
export const PROCEDURES_LINKS_LOAD_SUCCEED = "PROCEDURES_LINKS_LOAD_SUCCEED";
export const PROCEDURES_LINKS_LOAD_FAILED = "PROCEDURES_LINKS_LOAD_FAILED";

export const PROCEDURES_LINK_SAVE_INIT = "PROCEDURES_LINK_SAVE_INIT";
export const PROCEDURES_LINK_SAVE_SUCCEED = "PROCEDURES_LINK_SAVE_SUCCEED";
export const PROCEDURES_LINK_SAVE_FAILED = "PROCEDURES_LINK_SAVE_FAILED";

export const PROCEDURES_LINK_DELETE_INIT = "PROCEDURES_LINK_DELETE_INIT";
export const PROCEDURES_LINK_DELETE_SUCCEED = "PROCEDURES_LINK_DELETE_SUCCEED";
export const PROCEDURES_LINK_DELETE_FAILED = "PROCEDURES_LINK_DELETE_FAILED";
