export const V_CLASSROOM_NAMES_LOAD_INIT = "V_CLASSROOM_NAMES_LOAD_INIT";
export const V_CLASSROOM_NAMES_LOAD_SUCCEED = "V_CLASSROOM_NAMES_LOAD_SUCCEED";
export const V_CLASSROOM_NAMES_LOAD_FAILED = "V_CLASSROOM_NAMES_LOAD_FAILED";

export const V_CLASSROOM_LOAD_INIT = "V_CLASSROOM_LOAD_INIT";
export const V_CLASSROOM_LOAD_SUCCEED = "V_CLASSROOM_LOAD_SUCCEED";
export const V_CLASSROOM_LOAD_FAILED = "V_CLASSROOM_LOAD_FAILED";

export const V_CLASSROOM_ENTITY_LOAD_INIT = "V_CLASSROOM_ENTITY_LOAD_INIT";
export const V_CLASSROOM_ENTITY_LOAD_SUCCEED =
    "V_CLASSROOM_ENTITY_LOAD_SUCCEED";
export const V_CLASSROOM_ENTITY_LOAD_FAILED = "V_CLASSROOM_ENTITY_LOAD_FAILED";

export const ADD_V_CLASSROOM_INIT = "ADD_V_CLASSROOM_INIT";
export const ADD_V_CLASSROOM_SUCCEED = "ADD_V_CLASSROOM_SUCCEED";
export const ADD_V_CLASSROOM_FAILED = "ADD_V_CLASSROOM_FAILED";

export const SAVE_V_INIT = "SAVE_V_INIT";
export const SAVE_V_SUCCEED = "SAVE_V_SUCCEED";
export const SAVE_V_FAILED = "SAVE_V_FAILED";

export const DELETE_V_COURSE_INIT = "DELETE_V_COURSE_INIT";
export const DELETE_V_COURSE_SUCCEED = "DELETE_V_COURSE_SUCCEED";
export const DELETE_V_COURSE_FAILED = "DELETE_V_COURSE_FAILED";

export const DELETE_V_CLASSROOM_INIT = "DELETE_V_CLASSROOM_INIT";
export const DELETE_V_CLASSROOM_SUCCEED = "DELETE_V_CLASSROOM_SUCCEED";
export const DELETE_V_CLASSROOM_FAILED = "DELETE_V_CLASSROOM_FAILED";

export const SET_V_COURSE_DETAIL = "SET_V_COURSE_DETAIL";
