export const ENTITIES_LINKS_LOAD_INIT = "ENTITIES_LINKS_LOAD_INIT";
export const ENTITIES_LINKS_LOAD_SUCCEED = "ENTITIES_LINKS_LOAD_SUCCEED";
export const ENTITIES_LINKS_LOAD_FAILED = "ENTITIES_LINKS_LOAD_FAILED";

export const ENTITIES_LINK_SAVE_INIT = "ENTITIES_LINK_SAVE_INIT";
export const ENTITIES_LINK_SAVE_SUCCEED = "ENTITIES_LINK_SAVE_SUCCEED";
export const ENTITIES_LINK_SAVE_FAILED = "ENTITIES_LINK_SAVE_FAILED";

export const ENTITIES_LINK_DELETE_INIT = "ENTITIES_LINK_DELETE_INIT";
export const ENTITIES_LINK_DELETE_SUCCEED = "ENTITIES_LINK_DELETE_SUCCEED";
export const ENTITIES_LINK_DELETE_FAILED = "ENTITIES_LINK_DELETE_FAILED";
