export const FORMALITIES_LINKS_LOAD_INIT = "FORMALITIES_LINKS_LOAD_INIT";
export const FORMALITIES_LINKS_LOAD_SUCCEED = "FORMALITIES_LINKS_LOAD_SUCCEED";
export const FORMALITIES_LINKS_LOAD_FAILED = "FORMALITIES_LINKS_LOAD_FAILED";

export const FORMALITIES_LINK_SAVE_INIT = "FORMALITIES_LINK_SAVE_INIT";
export const FORMALITIES_LINK_SAVE_SUCCEED = "FORMALITIES_LINK_SAVE_SUCCEED";
export const FORMALITIES_LINK_SAVE_FAILED = "FORMALITIES_LINK_SAVE_FAILED";

export const FORMALITIES_LINK_DELETE_INIT = "FORMALITIES_LINK_DELETE_INIT";
export const FORMALITIES_LINK_DELETE_SUCCEED =
    "FORMALITIES_LINK_DELETE_SUCCEED";
export const FORMALITIES_LINK_DELETE_FAILED = "FORMALITIES_LINK_DELETE_FAILED";
