export const CE_LINKS_LOAD_INIT = "CE_LINKS_LOAD_INIT";
export const CE_LINKS_LOAD_SUCCEED = "CE_LINKS_LOAD_SUCCEED";
export const CE_LINKS_LOAD_FAILED = "CE_LINKS_LOAD_FAILED";

export const CE_LINK_SAVE_INIT = "CE_LINK_SAVE_INIT";
export const CE_LINK_SAVE_SUCCEED = "CE_LINK_SAVE_SUCCEED";
export const CE_LINK_SAVE_FAILED = "CE_LINK_SAVE_FAILED";

export const CE_LINK_DELETE_INIT = "CE_LINK_DELETE_INIT";
export const CE_LINK_DELETE_SUCCEED = "CE_LINK_DELETE_SUCCEED";
export const CE_LINK_DELETE_FAILED = "CE_LINK_DELETE_FAILED";
